Replace hyphen with underscore
Argparse doesn't support hyphen in argument names, so if the YAML
config contains hyphenated keys, yaml_config_override won't find a
matching key name.

Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.8/site-packages/yaml_config_override/__init__.py", line 52, in add_arguments
    if args[ckey] is not None:
KeyError: 'foo.bar-baz'